fix CI

diff --git a/.github/workflows/docker-compose.yaml b/.github/workflows/docker-compose.yaml
--- a/.github/workflows/docker-compose.yaml
+++ b/.github/workflows/docker-compose.yaml
@@ -51,10 +51,10 @@ jobs:
       run: pytest tests/*
 
     - name: Capture logs
-      run: docker compose logs --tail=20 > logs.txt
+      run: docker compose logs --tail=40 > logs.txt
 
     - name: Show logs
       run: cat logs.txt
 
     - name: Filter logs
-      run: cat logs.txt | grep -i -E "error|exception" | grep -v -i "hypercorn.error"
+      run: cat logs.txt | grep -i -E "error|exception" | grep -v -i "hypercorn.error" || true
